### ISSUE TITLE
Development version in ilw-grid.json is wrong

### ISSUE THREAD

**Issue by marvel-uiuc** [web-illinois/ilw-grid#3]
`ilw-grid.json` has `"development-version": "1.0.0-alpha"`, when it should have `"development-version": "1.0.0-alpha1"`.

**Comment by marvel-uiuc** [comment]
@bryanjonker-illinois I'd fix it, but I only have read access to this repository, so probably faster if you do it.

**Comment by bryanjonker-illinois** [comment]
Fixed -- thanks!
